'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ConnectionList
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TOZPatch.ConnectionList", GetType(ConnectionList).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lm8MLsKEEHtHwzio/1MpD9I3UB6APb80sCQxu/zDHGtnXGRW5OcTejHXu6vInnY6vUx6MgS84n+MyLzXq9Td9DyLFU6X3OPMBJweOZ1g7W7JbftUMmv6c254qqX7QrVT7ag9GVoWczlBT2LkUyBmd0+PBVTLnWCeRQ8aqQk/KvLMLyqEwTlZ0XHB3FZz6ghkuScnQwR8qzkvS6NC9u2i1xiwzjwYox0MqbKM40l9mIA=.
        '''</summary>
        Friend Shared ReadOnly Property Demo1() As String
            Get
                Return ResourceManager.GetString("Demo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sntdnJx1I3RaE9y13SNDnA72yWrRcLmHh00DgKgItMutcLXil2Ud2EBcxqNaEJDULOhSUF6NCmQKWQxhiWXVQCaGyZzoxXsCQe4rSRJqDQfrarN14vWcbiZZh91WmrQHGKxOoWn3nOiK9nMUs9eLPjYAGL6jYe5F5oiwEMXXdUtkytE184uaghlq12XtubgL.
        '''</summary>
        Friend Shared ReadOnly Property Live1() As String
            Get
                Return ResourceManager.GetString("Live1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6e1lTw4tXShWqsMif9LgR06iNnvqX8Vk+Mch7Xq6r+I/dIHApFTuSRdLA2o1kIGxbRqxaPlBng/qKazIPeK7fnXHBLIn9NSFBlVXYVSxtit+b7p5xS0JzSsDzKSemdtDyI69ADQr0ej8A8REbD7iWCoTdvA+/DHU/Z0lT2WEG8yYtokcUtK0mmumlrwaBqeM.
        '''</summary>
        Friend Shared ReadOnly Property Live2() As String
            Get
                Return ResourceManager.GetString("Live2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
