'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TOZPatch.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYlA+6WpVSTk97l8QsnuJE3AH6aDU69NXO0SUP7NoN2Jlk146G2OjUW3KM2ef7War3Pe5wyidEeagn50OCIfwYIjP+0OWnrx3kyjBEQ9Ah5LLiyWJC0AlV6C4lbJ17CE6evkkzE0E4kvHY+Tlv0/MdLd4QbPYN9jEiM66nA/0kVKT8RiNwALIdgbqWS1BiiAG1bzHRcaBNrsNyvQ46Tu9MvIykldv/ye8ky1kM2p0YleWZGXXDD23Tl4637XWBfU/18lB9LHTOfU52IjIpJrSSbLQxJLlGm4KtwkCiLbS9I7DXMI0ocyjzxjhOdcNwaVeSsrI4HEDsQXSYJuSA4kl+dHg3B3SSS42m7etX4XLxCoUt9UKORjzoV+HA3OqEFT/qt8Vg7BaShOxFxIho9muBVE=.
        '''</summary>
        Public ReadOnly Property DEV() As String
            Get
                Return ResourceManager.GetString("DEV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyPTmJt40l1DP6+www7dAvWerDObuHaRdXA+cUKvH+toZJmhnbB0nYE8b1qkcX8Vv/ECwMLhaHlZU8CYlowARxT/PazfQIyz4rVuMfJ4PF1JGCWZmAdtCon79WCdJmN+q+WfnhPdFn7Lhf1A+kw4pJ1L3pg56HOkiakK3ISTSZIK25UjGSCuG83F1GFfROsNPkgZOFxMu2QrefNExDmLfHo9LdJgnLyTbCHAkeI7jEZJ0B/CExcHAA1i8mEr0k3pyIli5HiPlxg5bfhQslX1l8Cw==.
        '''</summary>
        Public ReadOnly Property LIVE_1() As String
            Get
                Return ResourceManager.GetString("LIVE-1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyiRSA0jTuUTJsKyOsQKUYnL642hLd46dxjrzG4APCVCpwGCg5vDJW9Cs9PaWgQWho73PONdXU2r+ocPJR1zpZiJrIzhyZaCrr19zmMbT1U+DHKM4JbiuoSmYboGlqMAzXUkISWuiEVkGuH3F/QQfNVwqeSLqSdTt5e/Y9W1D6rDupjnkBBiBcMWBB7qBoCglXtx0ydIi0t2k3sV1kODfNi49OylTVEk/Ji3L0jtNZZgcRwUlq1a+FeQ6ya+4QX845D2rVQkS8GMzSp9P69q68ow==.
        '''</summary>
        Public ReadOnly Property LIVE_2() As String
            Get
                Return ResourceManager.GetString("LIVE-2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyNWnaX0Z2NU34R7Ebq4GokqSdW/WtmhmUNJm448ClxGx+EgeD2r6oZufPqZ6n768SnyC0F9H7cVKWF6Uu6W/asFvTtW+g65nn19gLp+4LJWWFUGnno5IqzIczyGPt7okS+oY/emGgJQNy5A8KflpBLYs84qRn0u6chsl3IPCDpgPKWVP4m971zOdwy5y+tqeslcNqSnbd0RasDQ20qMX28ex6Qf/HGlnJ972Ob04lfflZ8SeDuttKcSeInIQCRpt6nYOI+Ekrnm0/ELM5+O1ZmA==.
        '''</summary>
        Public ReadOnly Property LIVE_3() As String
            Get
                Return ResourceManager.GetString("LIVE-3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyXjsorQoiTT8xJASWykd0RJuLTyFqNCDNdBRlw6sPZ5Kj+UA3wzv/zcIqQ0mAEDwitUkGxrNM9TLsmzMV8xCMAqyZvF7Rv5AoC4+wvS+QHppYLkbXeEItH3Cy4IkErHsic1SuJiDyICm9PCXjF9fFagKXvaAUi6imOcrr8es0CWg8Y/TqVSu92YvIqmsdjaAijFyAsPrKjptdf5KBvebc6Knqud0PtCJu4sEZmwPZ/sGL8q1178RGFbxWSBWA0clpL0LMYUDpFP/KyIyC4TbnKxWVSoNihYpTahQZtUTjLpSBARxJ5evDDeicyo4rGuqwDvigEbc9hlrxaY3lztwKxlqE0OP+AYT5uRyhSyfFmc5NEw47BfdwN2foh6niA82z.
        '''</summary>
        Public ReadOnly Property LIVE_4() As String
            Get
                Return ResourceManager.GetString("LIVE-4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIygz42PFFVez8AhLkLOpiAZB8FVl4hxgmnZcKJoKDGzsVJSpxyHSvx3R1BCWXd85MaytpPHQu4yJiFE9FT+f84M4T9uj8zlJyDWEUhOM/7bdNI03eeGyjcwuiW/hrfOkOTBYkkksBN31z61PzDYIgltV4k3Q2HCR5tIyUL9Ta+kPhn+wwx0Xcbw2gQrUju6AJTgtT6s3Hcexbg1Nav0K6mwNSkutfoAECIMmfk8Fnkt5nFr7f6StNp8grWDGdVjrTteXw3tRuchckvH2j1UO4Pww==.
        '''</summary>
        Public ReadOnly Property LIVE_5() As String
            Get
                Return ResourceManager.GetString("LIVE-5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqThnshuObDuerOPEq9Onc4mbtmRQrl6uUc6v4vNFiZLGxGWyrptgsT8xUTMySYwLsxMSes29IO82tCx0xkTLqpnIc9UbgpDhC7KY+qrhhq9DOrWIwaULmfhDJ1xJ6VgfiDskkQ73GAe+RLQuUFNNOLNufFhxYaUW0qbT8I4bbrLPzLT+ZBLbazcTcXmXQm7xAu5K22eCCJZcFndxiLpF7J5fGNSxgdmEm20mQITCDEdIQ7dyW1za5BtLuXl5tQmCZ52DJ4YYZioJIRqIlzez7VV.
        '''</summary>
        Public ReadOnly Property STAGE() As String
            Get
                Return ResourceManager.GetString("STAGE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
